### ISSUE TITLE
Smart Proxy Chapter missing figs

### ISSUE THREAD

**Issue by farahfa** [sonatype/nexus-book#132]
https://github.com/sonatype/nexus-book/blob/master/chapter-smartproxy.asciidoc

The figures are not in the folder that they're suppose to be in.

**Comment by mosabua** [comment]
The folders are perfectly fine where they are. With the link above you are looking at the source code. The rendered output and readable version is available at http://books.sonatype.com/nexus-book/reference/smartproxy.html
