### ISSUE TITLE
404 link: Version 3.0 side nav link to "Raw Repositories and Sites" has a typo

### ISSUE THREAD

**Issue by eightnoneone** [sonatype/nexus-book#156]
TOC link is correct to 3.0/reference/sites.html but nav has 3.0/reference/site.html which is a 404.

**Comment by mosabua** [comment]
Thank you for noticing and reporting this bug. We will fix this later this week.

**Comment by eightnoneone** [comment]
For my education, is this something I could have done via PR? I didn't see where the side nav was generated in the book project.

**Comment by mosabua** [comment]
This is now controlled by a look and feel wrapper repository on its own. The change is trivial.. the work lies in publishing this out for all the docs.. 

https://github.com/sonatype/nexus-documentation-wrapper

**Comment by mosabua** [comment]
Fix is done. 

https://github.com/sonatype/nexus-book/commit/facee12fa9b1c08eba2f27570416119666687460
https://github.com/sonatype/nexus-documentation-wrapper/commit/d42eb96f4ea71041f700bb9bdba04f9662bd8c24

Deployment currently ongoing. Should be done shortly.
