### ISSUE TITLE
Confusing instructions for service installation

### ISSUE THREAD

**Issue by NetAppBlueDevil** [sonatype/nexus-book#30]
Section 3.7.1

4.c states
Change PIDDIR to a directory where this user has read/write permissions. In most Linux distributions, /var/run is only writable by root. The property you need to add to customize the PID file location is wrapper.pid. For more information about this property and how it would be configured in wrapper.conf, see: http://wrapper.tanukisoftware.com/doc/english/properties.html. 

So, do I just need to change the PIDDIR setting that is existing in the nexus script header, or do I additionally need to add this wrapper.pid?  Going to the linked tanuki pages is confusing because the property there is documented as wrapper.pidfile since updated in a later version to be java.wrapper.pidfile.  

I'm thinking I should only need to change PIDDIR, Grepping the script it appears that the tanuki property is handled internally and I should not care about it.

bash-4.1$ grep PID nexus
PIDDIR=/tmp
if [ "X$PIDDIR" = "X" ]
    PIDDIR="bin/jsw/$DIST_OS-$DIST_ARCH-$DIST_BITS"
FIRST_CHAR=`echo $PIDDIR | cut -c1,1`
    PIDDIR=$NEXUS_HOME/$PIDDIR
ANCHORFILE="$PIDDIR/$APP_NAME.anchor"
PIDFILE="$PIDDIR/$APP_NAME.pid"
    if [ -f "$PIDFILE" ]
        if [ -r "$PIDFILE" ]
            pid=`cat "$PIDFILE"`
                    rm -f "$PIDFILE"
                    echo "Removed stale pid file: $PIDFILE"
            echo "Cannot read $PIDFILE."
        rm -f "$PIDFILE"
        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=$APP_NAME wrapper.pidfile=\"$PIDFILE\" $ANCHORPROP $LOCKPROP"
        COMMAND_LINE="$CMDNICE \"$WRAPPER_CMD\" \"$WRAPPER_CONF\" wrapper.syslog.ident=$APP_NAME wrapper.pidfile=\"$PIDFILE\" wrapper.daemonize=TRUE $ANCHORPROP $IGNOREPROP $LOCKPROP"

**Comment by mosabua** [comment]
This should be all fixed in the current content. If not, please file a new ticket with details.
