### ISSUE TITLE
Confusing instructions for service installation, pt 2

### ISSUE THREAD

**Issue by NetAppBlueDevil** [sonatype/nexus-book#31]
Section 3.7.1

Item 5 states
Change the owner and group of your Nexus-related directories, including nexus-work configured in nexus.properties defaulting to sonatype-work/nexus, to the nexus user that will run the application. 

What is 'Nexus-related directories'?  Is this overall just meaning the full installation tree that we untarred earlier?  Just logs direectory?  Since the only related directories are the install and the sonatype-work  (I think), the wording would just be clearer to state that.

**Comment by mosabua** [comment]
This should be all fixed in the current content. If not, please file a new ticket with details.
