### ISSUE TITLE
Missing privilege type in section 6.13 under "Managing Privileges"

### ISSUE THREAD

**Issue by mikesmithson** [sonatype/nexus-book#35]
In section 6.13, the book says:
"Nexus has three types of privileges:"

It lists the following:
- application privileges
- repository target privileges

The third is omitted or the number of privilege types is 2. Please advise.

**Comment by joedragons** [comment]
Mike, it looks like there are three there, the formatting is bad.
See:
"* application privileges - covers actions a user can execute in Nexus,
*repository target privileges - governs the level of access a user has to a particular repository or repository target, and *repository view privileges - controls whether a user can view a repository"

Application privileges, repository target privileges and repository view privileges.
I will submit a request to get this patched up.
Thanks!
-JD

**Comment by joedragons** [comment]
Addressed in a5d5f9e

**Comment by joedragons** [comment]
Should be live now.  Thanks for the tip.
