### ISSUE TITLE
Re-implement section on migrating from Artifactory

### ISSUE THREAD

**Issue by andham** [sonatype/nexus-book#66]
In the docs for 2.11 the section on migrating from Artifactory (chapter 'Migrating to Nexus') has been removed. I can't find any commit message explaining the logic behind this so it's probably a mistake. Please re-implement this!

**Comment by joedragons** [comment]
Thanks this was indeed a typo.  The contents can be viewed in http://books.sonatype.com/nexus-book/reference/archiva.html because of it.  I have restore this the next time we push the book.

**Comment by mosabua** [comment]
Live and fixed now.

http://books.sonatype.com/nexus-book/reference/artifactory.html
