### ISSUE TITLE
Add description for all rulesets

### ISSUE THREAD

**Issue by andham** [sonatype/nexus-book#68]
Some rulesets of Nexus Pro v2.11.4 are not described:
* "No promote action allowed"
* "No release action allowed"
* "Profile target matcher"

**Comment by andham** [comment]
Regarding the "Profile target matcher" ruleset, see comment in https://issues.sonatype.org/i#browse/NXBOOK-876

**Comment by mosabua** [comment]
I can take that on when I am back.

**Comment by mosabua** [comment]
Updated documetation. Will publish shortly.

**Comment by mosabua** [comment]
https://github.com/sonatype/nexus-book/commit/e77932f80b33c660cd31508a2e0f69c61b7a4d88
