### ISSUE TITLE
Possible incorrect docs for ruleset

### ISSUE THREAD

**Issue by andham** [sonatype/nexus-book#69]
The docs for the "POM must not contain release repository" ruleset is incorrect I think. It says that no repository element is allowed, but the ruleset name indicates that no *release* repository is allowed (allowing snapshot repositories).

**Comment by mosabua** [comment]
Checked and fixed. Will publish shortly.

**Comment by mosabua** [comment]
https://github.com/sonatype/nexus-book/commit/e77932f80b33c660cd31508a2e0f69c61b7a4d88
