### ISSUE TITLE
NPM and perhaps other repositories require a service restart

### ISSUE THREAD

**Issue by jgroffen** [sonatype/nexus-book#71]
Following the NPM repository instructions to create a new NPM Proxy repository, it wasn't clear that a restart was required otherwise the following error would occur when using the repository:

400 - Schema com.bolyuba.nexus.plugin.npm.service.PackageRoot has no registered handler!

In wrapper logs it looked like the NPM plugin wasn't installed / enabled until after the restart, so it's probably only needed the first time any NPM repository type is created. It may also affect other repository types.

Ideally Nexus wouldn't need a restart, but in the meantime could the documentation be updated to reflect the possible need for a restart?

Using Nexus 2.11

**Comment by mosabua** [comment]
Just creating a repository should NOT require a restart. Upgrades however do as documented. What did you actually do to experience this problem?

**Comment by jgroffen** [comment]
Hello Mosabua, thanks for taking a look.

Followed the instructions at https://books.sonatype.com/nexus-book/reference/npm-proxying-registries.html

Parts 17.2 to 17.4.

Our first attempt did fail due to a folder permission problem (user running nexus couldn't create the backups folder). Once we fixed that we could create the proxy, hosted and group repositories. Maybe this left Nexus in an unstable state until reboot?

**Comment by mosabua** [comment]
Might well be... you should confirm that all files and folders are owned by the user running the Nexus server. Or at least it has to have full access. Any other tips @rseddon or @peterlynch ?

**Comment by peterlynch** [comment]
@jgroffen Nexus needs to be able to create directories under sonatype-work. It is a known issue that if the backup directory cannot be created, the npm plugin does not load.

Restart Nexus. If there is a problem starting the npm metadata database, the problem will be reported in the logs. To fix it, stop Nexus, delete the sonatype-work/nexus/db/npm directory, restart.

**Comment by jgroffen** [comment]
Thanks @peterlynch, the known issue you mention is exactly it. Didn't need to delete the sonatype-work/nexus/db/npm directory. Been using the npm proxy repo for a couple days now and it is performing great.

**Comment by alexandrehebert** [comment]
@peterlynch thanks, deleting the sonatype-work/nexus/db/npm worked for us !
